### PR TITLE
Revert "Revert "Allow using with existing event loops""

### PR DESCRIPTION
**Pull request by MrYsLab**
Reverts MrYsLab/pymata-express#19

### CODE REVIEW

**Comment by MrYsLab** [comment]
@DaAwesomeP I have merged your changes with some of mine and did a commit. This is working so far for me. There is no pypi release yet since I am still working on the tcp/ip interface, but you can download using the green download button if you wish to make sure I did not break anything for you.

Once I get the tcp/ip conde completed, I will be retesting all my examples. If I run into any issues I will let you know. When I release v 1.13, all the tests will have passed and your changes will available on pypi.

Thanks for your patience.

**Comment by DaAwesomeP** [comment]
No rush at all and thank you for applying the changes! I'll give it a test in a little while but it looks like those changes won't affect me as long as I set `autostart` to false. Have a nice day!

**Comment by MrYsLab** [comment]
@DaAwesomeP Version 1.13 was released and incorporates your pull request. Thanks for contributing and being patient.

**Comment by DaAwesomeP** [comment]
Thank you so much! Have a wonderful rest of your weekend.

**Pull request merged**
