### PR TITLE
Allow using with existing event loops

### PR DESCRIPTION
**Pull request by DaAwesomeP**
Hello again! I hope that you are well and staying safe!

I finally had more time to dig into the issue I was having in AIO, and I have solved all of it. This is a working solution but may not be how you wish to do it, so this pull is really just to show the issues and solution. I also did not update any docs or examples.

The first issue I was having was with `run_until_complete()`. This function expects the event loop to be clean and have nothing already running on it, or it will fail. This creates a requirement for pymata-express to be the first thing on the event loop. But this method seemed to be being used as a workaround to run async routines synchronously in `__init__()`. I looked and looked and looked for a workaround, but the only thing I could find that might work would be a combination of `create_task()` and `add_done_callback()` which looked like it would get messy really fast. The most pythonic and accepted solution appears to be to separate async calls that would have happened in `__init__` into a separate async function. Funnily enough, this is how both Python and NodeJS seem have adopted how to solve this issue in both of their async implementations.

This means that the `start()` function and autostart options can't really exist and `start_aio()` is now required to be run (breaking changes). It seems that this might be OK long-term since pymata4 exists for non-async usage. Also it seems OK to require an async start function call for a library that makes async calls.

Moving all of these calls to an async function means they can use `await` and are added and run in the event loop normally. So far this is all working fine for me even with a very filled and constantly cycled event loop.

The next issue surrounded the `shutdown()` method and the error handling for serial. Being able to use the shutdown method and the ability for it to be called automatically on error is a very nice convenience and ensures that the Arduino is properly closed without the user having to worry about it. I added a `close_loop_on_shutdown` option that allows shutdown to run without stopping and closing the event loop. This means that other existing non-pymata tasks are not affected and `shutdown_on_exception` means that pymata will be shutdown—not the whole application—when `close_loop_on_shutdown` is `False`. From trying to work around this in the same loop, closing the event loop used by other tasks is essentially the same as running `quit()` and stops the whole application.

All of these adjustments mean that Pymata can run in the same thread and event loop as everything else already in a Python application, and the user does not need to worry about isolating it at all. This is working beautifully for me so far!

Please let me know what you think!

### CODE REVIEW

**Comment by MrYsLab** [comment]
Sorry, you had to go through all that. I am doing the merge, but holding off on publishing this to pypi. I want to do a little test before creating a pypi release. It may be a few days before I get the chance to test. I will report here if all looks good or if there are any issues.
Thanks for the pull request.

**Comment by DaAwesomeP** [comment]
No problem! This was also a good learning experience for me for the lower-level parts of Python async.

**Comment by MrYsLab** [comment]
@DaAwesomeP 
I am reverting this pull request because it breaks all of the examples. I will be investigating the cause within the next week or so, but don't have the bandwidth to do this right now. If I can figure out the cause of the issues I will reinstate the pull request.

**Comment by DaAwesomeP** [comment]
Yes, since this removes `autostart` and `start() ` that is expected, unless you fixed that and it still failed. I'll give the ones I can try a test and see what I can find.

**Comment by MrYsLab** [comment]
I am proposing to reintroduce your pull request. Please look at this [version of pymata_express](https://gist.github.com/MrYsLab/fbc0a0288bc4f527f8bed0df87c2ed2f) and let me know if it works for your purposes.

I added an autostart flag which allows my examples to run unchanged by accepting the default of True, and I think for your scenarios if you set it to False, it will work as you had intended.

Please let me know if this works for you. If it does, you will need to do another pull request with my added changes. There does not seem to be an easy way to pick up the original pull request changes after the rever.

**Comment by DaAwesomeP** [comment]
Yeah, I think that should work fine! The only breaking change then is the removal of `start()`.

Just to confirm—all that you did was add back the autostart option and add back the autostart option to `__init__`, right? I can submit a new pull very soon.

**Comment by MrYsLab** [comment]
Yes. I added the additional parameter and if it is set to True, the start_aio is called from __ini__ (at the bottom of the method). 
I updated the file in the gist slightly after running it through a PEP-8 inspection.

I also did the same for [pymata_serial.py ](https://gist.github.com/MrYsLab/2a2ecc2f6f2742dd446983f93c0386d3) and made a minor change.

I am going to try to revert my revert, and hopefully, that will work and you won't have to create a new pull request. Give me a moment and I will get back to you and see if that works.

**Comment by DaAwesomeP** [comment]
Just a note for backward compatibility—the previous flag was called `autostart`, not `auto_start`.

I am basically done with a commit/pull if your revert doesn't work.

**Comment by MrYsLab** [comment]
Ok, that worked. You need not do anything. I will make the changes. I have some other changes going in as well. I am providing  support for the WDT humidity/temperature sensors and  tcp/ip support for connection to WiFi devices such as the ESP-8266 that use StandardFimataWiFi.

The release should be available within the week, but probably more like a day or two.

**Comment by DaAwesomeP** [comment]
Awesome! Thank you so much!

**Pull request merged**
