### PR TITLE
Add SPI Support

### PR DESCRIPTION
**Pull request by eigendude**
## Description

This PR adds SPI support.

I know we're in feature freeze, but I added an SPI driver according to the SPI spec: https://github.com/firmata/protocol/blob/master/spi.md

I ended up not using the code (yet), but I figured I'd post it in case someone found it useful.

### CODE REVIEW

**Comment by MrYsLab** [comment]
Thanks for the pull request, but I will not be merging it because I have a working version of [telemetrix](https://github.com/MrYsLab/telemetrix) and [telemetrix-aio](https://github.com/MrYsLab/telemetrix-aio) that includes SPI support as well some other features. The [server](https://github.com/MrYsLab/Telemetrix4Arduino) supports SPI for these clients. 

This pull request would require changes to FirmataExpess, and there is simply not enough room for implementation for Arduino Uno.

Thanks again.

**Comment by eigendude** [comment]
Thanks, as expected. Hopefully the PR title makes into a google search result for someone in need!

**Comment by eigendude** [comment]
@MrYsLab I forgot to mention, I evaluated telemetrix for my project and only chose firmata express because the familiar name helps sell the protocol to my teammates. Thanks for the wonderful code. If I need a new feature in the future I'll build on telemetrix!

**Comment by eigendude** [comment]
@MrYsLab Sorry for the second tag, but I think the time has come for me to switch to Telemetrix. Sure enough, I'm adding new features, and Sysex just makes life more difficult. In addition to upstreaming features, I could also contribute peripheral improvements that make adding features easier, like code organization or [adding CI](https://github.com/eigendude/pymata-express/commit/bf78165aa21fa26c3e42e2e25c2522ac7205f7e3). Would you be interested in improvements like this?

**Comment by MrYsLab** [comment]
@eigendude I replied via email sent to the email address on your GitHub page.

**Pull request closed without merging**
